<?php
$data = array (
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '蛋糕',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '12',
    'name' => '蛋糕',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '小灵通/固话充值卡',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '13',
    'name' => '小灵通/固话充值卡',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '移动手机充值卡',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '14',
    'name' => '移动手机充值卡',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '联通手机充值卡',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '15',
    'name' => '联通手机充值卡',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '商务礼物',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '16',
    'name' => '商务礼物',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '节日礼物',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '节日礼物',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '耳机',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '8',
    'name' => '耳机',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '电池',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '电池',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '读卡器和内存卡',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '11',
    'name' => '读卡器和内存卡',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '充电器',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '7',
    'name' => '充电器',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '个性定制',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '17',
    'name' => '个性定制',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '生日礼物',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '生日礼物',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '双模手机',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 2,
    'level' => 1,
    'id' => '5',
    'name' => '双模手机',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => 'CDMA手机',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '2',
    'name' => 'CDMA手机',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => 'GSM手机',
    'measure_unit' => '台',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '12',
    'level' => 1,
    'id' => '3',
    'name' => 'GSM手机',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '3G手机',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '4',
    'name' => '3G手机',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '鲜花',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '18',
    'name' => '鲜花',
  ),
);
?>